# Generated by Django 5.1.1 on 2024-09-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_risksurvey_worksite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RiskSurvey',
            new_name='Survey',
        ),
        migrations.RenameField(
            model_name='risknote',
            old_name='survey',
            new_name='Survey',
        ),
    ]
