# Generated by Django 5.1.1 on 2024-10-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_risknote_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='risknote',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
