# Generated by Django 5.1.1 on 2024-09-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_survey_risknote_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risknote',
            name='is_not_relevant',
        ),
        migrations.RemoveField(
            model_name='risknote',
            name='is_ok',
        ),
        migrations.AddField(
            model_name='risknote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='worksite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='api.worksite'),
        ),
    ]
