# Generated by Django 5.1.2 on 2024-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_accountsurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='165cd42eeec84504a820c05d287a347f', max_length=64, unique=True),
        ),
    ]
