# Generated by Django 5.1.2 on 2024-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='11379fcc800a447ca3b44cd84935ba0e', max_length=64, unique=True),
        ),
    ]
