# Generated by Django 5.1.1 on 2024-09-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_survey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='risknote',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
