# Generated by Django 5.1.2 on 2024-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_account_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_group',
        ),
        migrations.AddField(
            model_name='project',
            name='customer_account',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='data_area_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='worker_responsible_personnel_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='fd9562d0a98146a8bc49e5a99eada385', max_length=64, unique=True),
        ),
    ]
