# Generated by Django 5.1.2 on 2024-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_project_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='f5e2a84857704f39b63f31227c63bef4', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='scaffold_type',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='task',
            field=models.JSONField(),
        ),
    ]
