# Generated by Django 5.1.2 on 2024-11-22 13:20

from django.db import migrations, models
import json

# Migration changes
def convert_to_json(apps, schema_editor):
    Survey = apps.get_model('api', 'Survey')
    for survey in Survey.objects.all():
        # Convert string values to JSON arrays
        if isinstance(survey.scaffold_type, str):
            # Convert single string to array with one item
            survey.scaffold_type = json.dumps([survey.scaffold_type.strip('"').strip("'")])
        if isinstance(survey.task, str):
            survey.task = json.dumps([survey.task.strip('"').strip("'")])
        survey.save()

def convert_to_string(apps, schema_editor):
    Survey = apps.get_model('api', 'Survey')
    for survey in Survey.objects.all():
        if survey.scaffold_type:
            # Take first item from array when converting back
            array = json.loads(survey.scaffold_type)
            survey.scaffold_type = array[0] if array else ""
        if survey.task:
            array = json.loads(survey.task)
            survey.task = array[0] if array else ""
        survey.save()

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_remove_project_project_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='f5e2a84857704f39b63f31227c63bef4', max_length=64, unique=True),
        ),
        # First convert the data
        migrations.RunPython(
            convert_to_json,
            reverse_code=convert_to_string
        ),
        # Then alter the field types
        migrations.AlterField(
            model_name='survey',
            name='scaffold_type',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='task',
            field=models.JSONField(),
        ),
    ]
