# Generated by Django 5.1.2 on 2024-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_survey_access_code_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='30f021765e954539a93827d66325226d', max_length=64, unique=True),
        ),
    ]
