# Generated by Django 5.1.1 on 2024-09-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_risknote_survey_alter_survey_overseer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risknote',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
