# Generated by Django 5.1.2 on 2024-12-01 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_survey_access_code_alter_account_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to='api.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='number_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
