# Generated by Django 5.1.2 on 2024-11-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='9e05c1b3d18444e9b3b297b473b34b4b', max_length=64, unique=True),
        ),
    ]
