# Generated by Django 5.1.3 on 2024-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_survey_completed_at_survey_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risknote',
            name='language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='risknote',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='survey',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='translation_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
