# Generated by Django 5.1.2 on 2024-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(default='dfab28cabd2b41bf9299bb19a9386da1', max_length=64, unique=True),
        ),
    ]
