# Generated by Django 5.1.1 on 2024-09-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_survey_scaffold_risks_survey_surroundinds_risks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='surroundinds_risks',
            new_name='surroundings_risks',
        ),
    ]
