# Generated by Django 5.1.1 on 2024-09-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_surroundinds_risks_survey_surroundings_risks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='scaffold_risks',
            new_name='risks',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='surroundings_risks',
        ),
    ]
