# Generated by Django 5.1.1 on 2024-09-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_survey_overseer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='overseer',
        ),
    ]
